controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_change_locale:
    path: '/change-locale/{locale}'
    controller: 'App\Controller\LocaleController::changeLocale'

